title: Bottom
subtitle: by the Test
description: ????? An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
links:
  email: contact@your-lab.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: your-lab
  twitter: YourLabHandle
  linkedin: asdddd
  youtube: YourLabChannel
